In [1]:
#Support Vector 
#Kernal Functions --> Transform input features into higher dimention plan --> Seperate

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC

In [3]:
x = np.array([
    [-1,-1],
    [-2,-1],
    [1,1],
    [2,1]
])

In [4]:
y = np.array([1,1,2,2])

In [6]:
model = make_pipeline(StandardScaler(), SVC(gamma="auto"))

In [7]:
model.fit(x,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [9]:
model.predict([[-1,-2]])

array([1])

In [10]:
model.predict([[1,2]])

array([2])

In [11]:
model.predict([[-1,2]])

array([2])

In [12]:
model.predict([[-2,1]])

array([1])

In [13]:
from sklearn.datasets import load_iris

In [14]:
X,Y = load_iris(return_X_y=True)

In [16]:
X.shape

(150, 4)

In [17]:
Y.shape

(150,)

In [19]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
model2 = make_pipeline(StandardScaler(), SVC())

In [21]:
model2.fit(X,Y)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svc', SVC())])

In [22]:
X[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [25]:
y[:2]

array([1, 1])

In [24]:
model2.predict(X[:2])

array([0, 0])

In [29]:
y_pred = model2.predict(X)

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(Y,y_pred))

0.9733333333333334
