<h1><center><b>50 Startup Dataset</h1></center></b>

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [50]:
df = pd.read_csv("/content/50_Startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [51]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [52]:
X = df.iloc[:,:4].values
y = df.iloc[:,4].values

In [53]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [54]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [55]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [56]:
le = LabelEncoder()
X[:,3] = le.fit_transform(X[:,3])

In [57]:
X

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [58]:
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray()

In [59]:
X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [60]:
#dummy variable trap ---- removed/avoid

x = X[:,1:]

In [61]:
x

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [62]:
from sklearn.model_selection import train_test_split
train_data,test_data,train_label,test_label = train_test_split(x,y,test_size=0.2,random_state=0)

In [64]:
print("train_data : ",train_data.shape)
print("train_label : ",train_label.shape)
print("test_data : ",test_data.shape)
print("test_label : ",test_label.shape)

train_data :  (40, 149)
train_label :  (40,)
test_data :  (10, 149)
test_label :  (10,)


In [41]:
#Feature Scalling
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
train_data = scale.fit_transform(train_data)
test_data = scale.fit_transform(test_data)

In [42]:
test_data

array([[ 0.        ,  0.        ,  0.        , ..., -0.33333333,
         0.81649658, -0.65465367],
       [ 0.        ,  0.        ,  0.        , ...,  3.        ,
        -1.22474487, -0.65465367],
       [ 0.        ,  0.        ,  0.        , ..., -0.33333333,
         0.81649658, -0.65465367],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.33333333,
        -1.22474487,  1.52752523],
       [ 0.        ,  0.        ,  0.        , ..., -0.33333333,
         0.81649658, -0.65465367],
       [ 0.        ,  0.        ,  0.        , ..., -0.33333333,
         0.81649658, -0.65465367]])

In [65]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(train_data,train_label)

In [66]:
y_pred = model.predict(test_data)

In [67]:
y_pred

array([110421.259933  ,  99635.0731779 , 110421.259933  , 110421.259933  ,
       110421.259933  , 119829.39601805, 119829.39601805, 119829.39601805,
       110421.259933  , 110421.259933  ])

In [68]:
test_label

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [69]:
from sklearn.metrics import mean_squared_error
print("MSE : ",mean_squared_error(test_label,y_pred))

MSE :  1620102725.9251297
