In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
X = np.array([
    [1,1],
    [1,2],
    [2,2],
    [2,3]
])

In [3]:
Y = np.dot(X, np.array([1,2])) + 3

In [4]:
Y

array([ 6,  8,  9, 11])

In [5]:
model = LinearRegression().fit(X,Y)

In [6]:
model.predict([[3,4]])

array([14.])

In [7]:
import pandas as  pd

In [8]:
df = pd.read_csv("/content/winequality-red.csv", sep=";")

In [9]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [10]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [22]:
X = df.iloc[:,:11].values

In [23]:
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [24]:
Y = df.iloc[:,11].values

In [25]:
Y

array([5, 5, 5, ..., 6, 5, 6])

In [26]:
from sklearn.model_selection import train_test_split
train_data,test_data,train_label,test_label = train_test_split(X, Y, test_size=0.2, random_state=0)

In [27]:
print("train_data : ",train_data.shape)
print("train_label : ",train_label.shape)
print("test_data : ",test_data.shape)
print("test_label : ",test_label.shape)

train_data :  (1279, 11)
train_label :  (1279,)
test_data :  (320, 11)
test_label :  (320,)


In [28]:
model2 = LinearRegression().fit(train_data,train_label)


In [29]:
y_pred = model2.predict(test_data)

In [35]:
model2.score(test_data,test_label)

0.3283887639580225

<h1><center><b>Important Not</b></center></h1>


# **Accuracy score is only for classification problems. For regression problems you can use: R2 Score, MSE (Mean Squared Error), RMSE (Root Mean Squared Error).**

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [31]:
accuracy_score(test_label,y_pred)

ValueError: ignored

In [32]:
cm = confusion_matrix(test_label,y_pred)

ValueError: ignored

In [33]:
test_label.shape

(320,)

In [34]:
y_pred.shape

(320,)