In [3]:
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
n_sample, n_feature = 10,5

In [4]:
r = np.random.RandomState(0)

In [6]:
x = r.randn(n_sample, n_feature)
y = r.randn(n_sample)

In [7]:
x

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [8]:
y

array([-0.89546656,  0.3869025 , -0.51080514, -1.18063218, -0.02818223,
        0.42833187,  0.06651722,  0.3024719 , -0.63432209, -0.36274117])

In [9]:
x.shape

(10, 5)

In [10]:
y.shape

(10,)

In [12]:
model = make_pipeline(StandardScaler(), SVR())

In [13]:
model.fit(x,y)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svr', SVR())])

In [14]:
model.predict(x)

array([-0.79557751,  0.24047052, -0.41085292, -0.76315279, -0.05308119,
        0.32815955, -0.03353056, -0.22913123, -0.53404965, -0.26263477])

In [15]:
y

array([-0.89546656,  0.3869025 , -0.51080514, -1.18063218, -0.02818223,
        0.42833187,  0.06651722,  0.3024719 , -0.63432209, -0.36274117])